
IMPORT INTO SRC_RETAIL_2.CASH_POINT FROM LOCAL CSV 
FILE '<local path>/cash_point.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;

IMPORT INTO SRC_RETAIL_2.PRODUCT FROM LOCAL CSV 
FILE '<local path>/product.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;

IMPORT INTO SRC_RETAIL_2.PROD_CATEGORY FROM LOCAL CSV 
FILE '<local path>/prod_category.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;

IMPORT INTO SRC_RETAIL_2.PROD_GROUP FROM LOCAL CSV 
FILE '<local path>/prod_group.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;

IMPORT INTO SRC_RETAIL_2.SALE FROM LOCAL CSV 
FILE '<local path>/sale.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;

IMPORT INTO SRC_RETAIL_2.STORE FROM LOCAL CSV 
FILE '<local path>/store.csv'
COLUMN SEPARATOR = ';'
ROW SEPARATOR = 'LF'
SKIP = 1
;


